name: Lint and check documentation
on: [push]
permissions:
  contents: write
  statuses: write
jobs:
  autofix:
    name: Autofix any basic errors
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install markdownlint
      run: npm install -g markdownlint && npm install -g markdownlint-cli2
    - name: Install textlint and terminology rules
      run: npm install -g textlint && npm install -g textlint-filter-rule-allowlist && npm install -g textlint-rule-terminology
    - name: Setup Git
      run: git config user.name "Github Actions" && git config user.email "noreply@github.com"
    - name: Run markdownlint in fix mode
      run: find . -type f -iname \*.md -exec markdownlint-cli2-fix {} \;
    - name: Run textlint in fix mode
      run: find . -type f -iname \*.md -exec textlint --fix {} \;
    - name: Commit any changes to the branch
      run: |-
        git update-index -q --refresh
        if git diff-index --exit-code --ignore-submodules --quiet HEAD; then
          echo "No changes made!"
        else
          git commit -am 'Autofix linter errors'
          git push
        fi
  lint:
    needs: [autofix]
    name: Lint docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .
          VALIDATE_JSCPD: false
          VALIDATE_OPENAPI: false
          FILTER_REGEX_EXCLUDE: "^.*yaml/.*"
          KUBERNETES_KUBEVAL_OPTIONS: "--ignore-missing-schemas"
  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@8f0156cc69c9f6dfaad8aae63f93a7a604b95b5f
        with:
          config-file: '.linkcheck.config'
